--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/fernanACM/BroadcastACM
build-by-default: true
branches:
- PM5
- PM4
projects:
  BroadcastACM:
    path: ""
    icon: icon-broadcastacm.png
    libs:
      - src: ACM-PocketMine-MP/Commando/Commando
        version: ^3.2.0
        branch: PM5
      - src: muqsit/simplepackethandler/SimplePacketHandler
        version: ^0.1.3
      - src: Vecnavium/FormsUI/FormsUI
        version: ^1.1.3
      - src: ACM-PocketMine-MP/libPiggyUpdateChecker/libPiggyUpdateChecker
        version: ^2.0.0
      - src: ACM-PocketMine-MP/DiscordWebhookAPI/DiscordWebhookAPI
        version: ^1.0.3
    lint:
      phpstan: false
...
